import { useMemo, useState } from 'react';
import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowDown, ArrowRight, ArrowUpRight, Download, ExternalLink, Github, Linkedin, Mail, MapPin, FileText, Cpu, CircuitBoard, Radio, Cloud, ChevronDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ProjectVisual } from '@/components/portfolio/ProjectVisual';
import { additionalProjects, experience, featuredProjects, person, skills } from '@/data/portfolio';

export const Route = createFileRoute('/')({
  head: () => ({ links: [{ rel: 'canonical', href: '/' }], meta: [
    { title: 'Perikala Kartheek | ECE Graduate | Embedded Systems | IoT | DevOps' },
    { name: 'description', content: 'Portfolio of Perikala Kartheek, an Electronics and Communication Engineering graduate working across embedded systems, IoT, automation, AI/ML, DevOps, and cloud fundamentals.' },
    { property: 'og:title', content: 'Perikala Kartheek | ECE Graduate | Embedded Systems | IoT | DevOps' },
    { property: 'og:description', content: 'Portfolio of Perikala Kartheek, an Electronics and Communication Engineering graduate working across embedded systems, IoT, automation, AI/ML, DevOps, and cloud fundamentals.' },
    { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' },
  ] }),
  component: Index,
});

const categories = ['All', 'Embedded', 'IoT', 'Automation', 'AI / ML'] as const;

function SectionHeading({ number, label, title, description }: { number: string; label: string; title: string; description?: string }) {
  return <div className="section-heading"><div><span className="section-kicker"><span>{number}</span> / {label}</span><h2>{title}</h2></div>{description && <p>{description}</p>}</div>;
}

function Index() {
  const [filter, setFilter] = useState<(typeof categories)[number]>('All');
  const [expanded, setExpanded] = useState<string | null>(null);
  const filtered = useMemo(() => additionalProjects.filter(project => filter === 'All' || (filter === 'AI / ML' ? /AI|Fuzzy|Computer Vision/.test(project.category) : project.category.includes(filter))), [filter]);
  const resumeAvailable = Boolean(person.resumeUrl);

  return <main>
    <section className="hero" id="home">
      <div className="hero-schematic" aria-hidden="true"><div className="schematic-grid" /><div className="schematic-ring ring-one" /><div className="schematic-ring ring-two" /><div className="schematic-ring ring-three" /><div className="schematic-cross cross-one">+</div><div className="schematic-cross cross-two">+</div><div className="schematic-line line-one" /><div className="schematic-line line-two" /><div className="schematic-chip chip-one">SENSOR / INPUT</div><div className="schematic-chip chip-two">CONTROL / LOGIC</div><div className="schematic-chip chip-three">CLOUD / OUTPUT</div><div className="schematic-core"><Cpu strokeWidth={1} /></div></div>
      <div className="container-wide hero-inner"><div className="hero-content"><div className="hero-status"><span className="status-pulse" /> OPEN TO ENGINEERING OPPORTUNITIES <span className="status-separator">/</span> ONGOLE, INDIA</div><p className="hero-pretitle">HELLO, I'M</p><h1>Perikala<br /><span>Kartheek<span className="hero-period">.</span></span></h1><div className="hero-title"><span className="hero-title-rule" /><p>Electronics & Communication Engineering Graduate<br /><strong>Building Embedded, IoT, Automation and Cloud-Ready Systems</strong></p></div><p className="hero-summary">ECE graduate with hands-on experience across embedded systems, sensor-based monitoring, RFID/NFC integration, automation, IoT telemetry, Python scripting, Linux, Git, AWS fundamentals, and machine-learning concepts.</p><div className="hero-actions"><Button size="lg" asChild><a href="#projects">View Projects <ArrowUpRight /></a></Button>{resumeAvailable ? <Button size="lg" variant="outline" asChild><a href={person.resumeUrl} download><Download /> Download Resume</a></Button> : <Button size="lg" variant="outline" disabled title="Resume PDF coming soon"><Download /> Resume coming soon</Button>}</div><div className="hero-social"><a href={person.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin size={16} /> LinkedIn <ArrowUpRight size={13} /></a><a href={person.github} target="_blank" rel="noopener noreferrer"><Github size={16} /> GitHub <ArrowUpRight size={13} /></a><a href="#contact"><Mail size={16} /> Contact Me <ArrowUpRight size={13} /></a></div></div></div>
      <div className="hero-bottom container-wide"><span>ENGINEER <i /> BUILDER <i /> LEARNER</span><a href="#projects">SCROLL TO EXPLORE <ArrowDown size={14} /></a><span>01 / 09</span></div>
    </section>

    <section className="intro-strip"><div className="container-wide intro-strip-inner"><div><CircuitBoard /><span>EMBEDDED SYSTEMS</span></div><div><Radio /><span>IoT & AUTOMATION</span></div><div><Cpu /><span>AI / ML EXPOSURE</span></div><div><Cloud /><span>DEVOPS & CLOUD FUNDAMENTALS</span></div></div></section>

    <section className="section projects-section" id="projects"><div className="container-wide"><SectionHeading number="01" label="SELECTED WORK" title="Projects built around real systems." description="From sensor inputs to intelligent actions. A closer look at engineering work across embedded systems, IoT and automation." /><div className="featured-list">{featuredProjects.map((project, index) => <Link to="/projects/$slug" params={{ slug: project.slug }} className="featured-project" key={project.slug}><div className="project-image"><ProjectVisual visual={project.visual} /><span className="project-image-index">0{index + 1} / FEATURED</span></div><div className="project-copy"><span className="project-category">{project.category} <span>/</span> {project.dates}</span><h3>{project.title}</h3><p>{project.description}</p><div className="project-tags">{project.technologies.slice(0, 5).map(tech => <span key={tech}>{tech}</span>)}</div><span className="project-link">Explore project <ArrowUpRight size={18} /></span></div></Link>)}</div></div></section>

    <section className="section additional-section"><div className="container-wide"><SectionHeading number="02" label="MORE EXPLORATIONS" title="Further engineering explorations." description="Academic projects, engineering ideas and research concepts. Labels reflect the available information, not commercial work." /><div className="filter-row" role="group" aria-label="Filter projects">{categories.map(category => <Button key={category} variant={filter === category ? 'default' : 'outline'} size="sm" aria-pressed={filter === category} onClick={() => setFilter(category)}>{category}</Button>)}</div><div className="additional-grid">{filtered.map(project => <article className="additional-card" key={project.slug}><Link to="/projects/$slug" params={{ slug: project.slug }} className="additional-visual-link" aria-label={`View ${project.title}`}><ProjectVisual visual={project.visual} compact /></Link><div className="additional-card-body"><span className="project-category">{project.type} / {project.category}</span><h3><Link to="/projects/$slug" params={{ slug: project.slug }}>{project.title}</Link></h3><p>{project.description}</p><Link to="/projects/$slug" params={{ slug: project.slug }} className="small-arrow-link">View project <ArrowUpRight size={16} /></Link></div></article>)}</div>{filtered.length === 0 && <p className="empty-filter">No projects in this category yet.</p>}</div></section>

    <section className="section skills-section" id="skills"><div className="container-wide"><SectionHeading number="03" label="TECHNICAL TOOLKIT" title="The tools behind the work." description="Hands-on project tools alongside areas of foundational knowledge and ongoing learning." /><div className="skills-grid">{skills.map((group, index) => <div className="skill-group" key={group.title}><div className="skill-group-top"><span>0{index + 1}</span><span className="skill-mark">✳</span></div><h3>{group.title}</h3><div className="skill-tags">{group.items.map(item => <span key={item}>{item}</span>)}</div></div>)}</div></div></section>

    <section className="section about-section" id="about"><div className="container-wide about-grid"><div><span className="section-kicker"><span>04</span> / ABOUT ME</span><h2>Curious about how things work. Focused on making them work.</h2><div className="about-meta"><MapPin size={16} /> Ongole, Andhra Pradesh, India</div></div><div className="about-copy"><p>I am an Electronics and Communication Engineering graduate with hands-on experience in embedded systems, IoT-based monitoring, sensor integration, RFID/NFC automation, and system integration.</p><p>Through projects and virtual internships, I have also built a foundation in Python scripting, Linux, Git, AWS fundamentals, and machine-learning concepts.</p><p>I enjoy taking a system from an idea through design, hardware-software integration, testing, automation, and documentation. Right now, I’m especially interested in embedded systems, automation, DevOps, cloud technologies, and practical AI-enabled engineering solutions.</p><a className="text-link" href={`mailto:${person.email}`}>Get in touch <ArrowUpRight size={17} /></a></div></div></section>

    <section className="section experience-section" id="experience"><div className="container-wide"><SectionHeading number="05" label="EXPERIENCE" title="Learning by doing." description="Internships and campus responsibilities that shaped my engineering approach." /><div className="timeline">{experience.map((item, index) => <div className="timeline-item" key={item.role}><span className="timeline-dot" /><div className="timeline-date">{item.period}</div><div className="timeline-content"><span className="timeline-index">0{index + 1} / EXPERIENCE</span><h3>{item.role}</h3><span className="timeline-place">{item.place}</span><p>{item.description}</p></div></div>)}</div></div></section>

    <section className="section devops-section" id="devops"><div className="container-wide"><SectionHeading number="06" label="EVOLVING PATH" title="DevOps & Cloud Journey" description="A developing foundation, not a claim of professional DevOps experience." /><div className="journey-track">{['Linux', 'Git', 'Maven', 'Docker', 'Jenkins', 'AWS', 'CI/CD'].map((step, index) => <div className="journey-step" key={step}><span className="journey-number">{String(index + 1).padStart(2, '0')}</span><span className="journey-name">{step}</span>{index < 6 && <ArrowRight size={16} className="journey-arrow" />}</div>)}</div><div className="journey-foot"><p>Currently developing stronger hands-on experience in DevOps, cloud infrastructure, automation, and deployment workflows.</p><span>CONTAINERIZATION / BASIC CLOUD INFRASTRUCTURE / DELIVERY WORKFLOWS</span></div></div></section>

    <section className="section credentials-section" id="certifications"><div className="container-wide credentials-grid"><div><span className="section-kicker"><span>07</span> / CREDENTIALS</span><h2>Certifications & participation.</h2><p>Learning experiences and participation beyond the classroom.</p></div><div className="credential-list">{['AI-ML Virtual Internship — EduSkills', 'Embedded System Developer Internship — EduSkills', 'Machine Learning Internship — Intern Orbit', 'Excel Dashboards for Data Analysis — WsCube Tech', 'QIS HACK X 24 Hackathon — Participation Certificate'].map((item, index) => <div className="credential-item" key={item}><span>{String(index + 1).padStart(2, '0')}</span><strong>{item}</strong><FileText size={18} aria-hidden="true" /></div>)}<p className="materials-note">Certificate images can be added when available.</p></div></div></section>

    <section className="section education-section" id="education"><div className="container-wide"><SectionHeading number="08" label="EDUCATION & ACTIVITIES" title="Where it started." /><div className="education-layout"><div className="education-main"><span className="education-overline">2022 — 2026 / UNDERGRADUATE</span><h3>B.Tech in Electronics and Communication Engineering</h3><p>QIS College of Engineering and Technology</p><span className="education-cgpa">CGPA: To be updated with official value</span></div><div className="education-secondary"><div><span>2022 / INTERMEDIATE</span><h4>Sri Chaitanya Junior College</h4></div><div><span>2020 / 10TH</span><h4>Sri Sai High School, Paramita</h4></div></div></div><div className="activities"><span className="section-kicker">BEYOND THE LAB</span><div>{['Class Representative, ECE Department', 'QIS HACK X 24 participation', 'UNLEASH WOMEN / QIS WIE Affinity Group participation', 'Digital Media and Cyber Laws Literacy Camp — Student Coordinator', 'Volleyball Team Player', 'Volunteer, QIS FEST 2025'].map(activity => <span key={activity}>{activity}</span>)}</div></div></div></section>

    <section className="section resume-section"><div className="container-wide resume-inner"><div><span className="section-kicker">PROFILE / PDF</span><h2>A closer look at my background.</h2><p>Explore projects, skills, internships, and education in one place.</p></div><div className="resume-actions">{resumeAvailable ? <><Button size="lg" asChild><a href={person.resumeUrl} download><Download /> Download Resume</a></Button><Button variant="outline" size="lg" asChild><a href={person.resumeUrl} target="_blank" rel="noopener noreferrer"><ExternalLink /> View Resume</a></Button></> : <><Button size="lg" disabled title="Resume PDF not yet provided"><Download /> Download Resume</Button><Button variant="outline" size="lg" disabled title="Resume PDF not yet provided"><ExternalLink /> View Resume</Button><span className="resume-note">Resume PDF not available yet.</span></>}</div></div></section>

    <section className="section contact-section" id="contact"><div className="container-wide contact-inner"><span className="section-kicker"><span>09</span> / CONTACT</span><h2>Let's <em>Connect.</em></h2><p>Open to opportunities in embedded systems, automation, DevOps, cloud, IoT, and related engineering roles.</p><a className="contact-email" href={`mailto:${person.email}`}>{person.email}<ArrowUpRight /></a><div className="contact-actions"><Button size="lg" asChild><a href={`mailto:${person.email}`}><Mail /> Email Me <ArrowUpRight /></a></Button><Button variant="outline" size="lg" asChild><a href={person.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin /> LinkedIn <ArrowUpRight /></a></Button><Button variant="outline" size="lg" asChild><a href={person.github} target="_blank" rel="noopener noreferrer"><Github /> GitHub <ArrowUpRight /></a></Button></div><button className="contact-phone-toggle" onClick={() => setExpanded(expanded === 'phone' ? null : 'phone')} aria-expanded={expanded === 'phone'}>Phone contact <ChevronDown size={15} /></button>{expanded === 'phone' && <a className="contact-phone" href={`tel:${person.phone.replaceAll(' ', '')}`}>{person.phone}</a>}</div></section>
  </main>;
}
